version: '3'

networks:
  fate-network:
services:
  mysql_master:
    image: mysql:8
    env_file:
      - ./master/mysql_master.env
    container_name: "mysql_master"
    restart: "no"
    ports:
      - 4406:3306
    volumes:
      - ./master/conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./master/data:/var/lib/mysql
    networks:
      - fate-network

  mysql_slave:
    image: mysql:8
    env_file:
      - ./slave/mysql_slave.env
    container_name: "mysql_slave"
    restart: "no"
    ports:
      - 5506:3306
    depends_on:
      - mysql_master
    volumes:
      - ./slave/conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./slave/data:/var/lib/mysql
    networks:
      - fate-network



