version: '3'

networks:
  fate-network:
services:
  mysql_master:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=safe@2019
      - MYSQL_LOWER_CASE_TABLE_NAMES=0
    container_name: "mysql_master"
    restart: always
    ports:
      - 4406:3306
    volumes:
      - ./master/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./master/data:/var/lib/mysql
    networks:
      - fate-network

  mysql_slave:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=safe@2019
      - MYSQL_LOWER_CASE_TABLE_NAMES=0
    container_name: "mysql_slave"
    restart: always
    ports:
      - 5506:3306
    depends_on:
      - mysql_master
    volumes:
      - ./slave/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./slave/data:/var/lib/mysql
    networks:
      - fate-network



